# Generated by Django 4.1.2 on 2022-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_calif_movie_rate_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='serie',
            name='rate',
            field=models.IntegerField(max_length=1),
        ),
    ]
