# Generated by Django 4.1.2 on 2022-11-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_rating_movie_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='serie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='serie'),
        ),
    ]
