# Generated by Django 4.1.2 on 2022-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_movie_rate_alter_serie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='seasons',
            field=models.IntegerField(max_length=2),
        ),
    ]
