# Generated by Django 4.1.2 on 2022-11-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_comment_serie_serie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together={('name', 'category')},
        ),
    ]
