# Generated by Django 4.1.2 on 2022-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_serie_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='seasons',
            field=models.IntegerField(),
        ),
    ]
