# Generated by Django 4.1.2 on 2022-11-17 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_serie_comments_serie_owner_alter_movie_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='comments',
        ),
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(related_name='comments_owned', through='catalog.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
