# Generated by Django 4.1.2 on 2022-11-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_movie_rate_alter_serie_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='updated_at',
        ),
    ]
