# Generated by Django 4.1.2 on 2022-11-17 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_remove_serie_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='comments',
            field=models.ManyToManyField(related_name='serie_comments', through='catalog.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(related_name='movie_comments', through='catalog.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
