# Generated by Django 4.1.2 on 2022-11-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_serie_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='comments',
        ),
    ]
